version: '3'

services:
  web:
    build: .
    ports:
      - "8050:5000"
    depends_on:
      - mongo
    environment:
      - MONGO_HOST=mongo
    networks:
      - my_network

  mongo:
    image: mongo
    restart: always
    volumes:
      - ./mongo_data:/data/db
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
